# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.', unique=True, verbose_name='Template uuid')),
                ('name', models.CharField(help_text='Template Name.', max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(help_text='Template Description.', verbose_name='Template Description')),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Template schema.')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(db_index=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'verbose_name': 'Template',
            },
        ),
    ]
