apiVersion: v1
kind: ReplicationController
metadata:
  name: db-sample
  labels:
    name: db-sample
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: db-sample
    spec:
      containers:
      - name: guestbook
        image: inforian/sam:v7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:

